Revert "Use <linux/eventpoll.h> to implement <sys/epoll.h>."
This reverts commit 893fd97cdcfbb040c938acac42658c885da879ee.

This fixes the following build errors:

bionic/libc/include/sys/epoll.h:67:8: error: redefinition of 'epoll_event'
struct epoll_event {
       ^
out/target/product/marlin/obj/KERNEL_OBJ/usr/include/linux/eventpoll.h:59:8: note: previous definition is here
struct epoll_event {
       ^
1 error generated.

Change-Id: I808b42560e55cb6c8a4ff82cdf361d17a6495b4f