Revert "Use <linux/eventpoll.h> to implement <sys/epoll.h>."
This reverts commit 893fd97cdcfbb040c938acac42658c885da879ee.

This fixes the following build errors:

FAILED: out/target/product/marlin/obj_arm/SHARED_LIBRARIES/camera.msm8996_intermediates/QCamera2Factory.o
/bin/bash -c "PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-4053586/bin/clang++ 	-I device/google/marlin/camera/QCamera2/../mm-image-codec/qexif -I device/google/marlin/camera/QCamera2/../mm-image-codec/qomx_core -I device/google/marlin/camera/QCamera2/include -I device/google/marlin/camera/QCamera2/stack/common -I device/google/marlin/camera/QCamera2/stack/mm-camera-interface/inc -I device/google/marlin/camera/QCamera2/util -I device/google/marlin/camera/QCamera2/HAL3 -I hardware/libhardware/include/hardware -I hardware/qcom/media/msm8996/libstagefrighthw -I out/target/product/marlin/obj/include/mm-core/omxcore -I system/core/include/cutils -I system/core/include/system -I system/media/camera/include/system -I device/google/marlin/camera/QCamera2/HAL -I out/target/product/marlin/obj/KERNEL_OBJ/usr/include -I out/target/product/marlin/obj/include/qcom/display -I hardware/qcom/display/msm8996/libqservice -I device/google/marlin/camera/QCamera2 -I out/target/product/marlin/obj_arm/SHARED_LIBRARIES/camera.msm8996_intermediates -I out/target/product/marlin/gen/SHARED_LIBRARIES/camera.msm8996_intermediates -I libnativehelper/include_deprecated \$(cat out/target/product/marlin/obj_arm/SHARED_LIBRARIES/camera.msm8996_intermediates/import_includes)  -I system/core/include -I system/media/audio/include -I hardware/libhardware/include -I hardware/libhardware_legacy/include -I hardware/ril/include -I libnativehelper/include -I frameworks/native/include -I frameworks/native/opengl/include -I frameworks/av/include -isystem out/target/product/marlin/obj/include -isystem device/google/marlin/kernel-headers -isystem bionic/libc/arch-arm/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -c  -fno-exceptions -Wno-multichar -ffunction-sections -fdata-sections -funwind-tables -fstack-protector-strong -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2 -fno-short-enums -no-canonical-prefixes -DNDEBUG -g -Wstrict-aliasing=2 -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -DNDEBUG -UDEBUG -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined -fdebug-prefix-map=\$PWD/= -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -nostdlibinc -msoft-float -mfloat-abi=softfp -mfpu=neon -mcpu=krait -mfpu=neon-fp-armv8 -D__ARM_FEATURE_LPAE=1 -target arm-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin  -Wsign-promo -Wno-inconsistent-missing-override -Wno-null-dereference -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -fvisibility-inlines-hidden -std=gnu++14 -mthumb -Os -fomit-frame-pointer -fno-strict-aliasing  -fno-rtti -Wall -Wextra -Werror -DSYSTEM_HEADER_PREFIX=sys -DHAS_MULTIMEDIA_HINTS -D_ANDROID -DVANILLA_HAL -std=c++14 -std=gnu++1z -DDEFAULT_DENOISE_MODE_ON -DHAL3 -DQCAMERA_REDEFINE_LOG -DVENUS_PRESENT -DUBWC_PRESENT -fPIC -D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type     -MD -MF out/target/product/marlin/obj_arm/SHARED_LIBRARIES/camera.msm8996_intermediates/QCamera2Factory.d -o out/target/product/marlin/obj_arm/SHARED_LIBRARIES/camera.msm8996_intermediates/QCamera2Factory.o device/google/marlin/camera/QCamera2/QCamera2Factory.cpp"
In file included from device/google/marlin/camera/QCamera2/QCamera2Factory.cpp:39:
In file included from device/google/marlin/camera/QCamera2/HAL/QCamera2HWI.h:42:
In file included from device/google/marlin/camera/QCamera2/util/QCameraDisplay.h:35:
In file included from system/core/libutils/include/utils/Looper.h:25:
bionic/libc/include/sys/epoll.h:67:8: error: redefinition of 'epoll_event'
struct epoll_event {
       ^
out/target/product/marlin/obj/KERNEL_OBJ/usr/include/linux/eventpoll.h:59:8: note: previous definition is here
struct epoll_event {
       ^
1 error generated.

Change-Id: I808b42560e55cb6c8a4ff82cdf361d17a6495b4f